app = 'dr-rag-api'
primary_region = 'ord'

[build]

[env]
  DATABASE_URL = 'sqlite:////data/api_users.db'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = 'uvicorn api.main:app --host 0.0.0.0 --port 8000'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'

[mounts]
  source = 'dr_rag_data'
  destination = '/data'

[[services.http_checks]]
  interval = 10000
  grace_period = "30s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = 5000
